- name: Update Packages (dnf)
  dnf:
    name: '*'
    state: latest

- name: Update && Upgrade Packages (deb)
  apt:
    update_cache: yes
    upgrade: yes

- name: Install Packages
  package:
    name: '{{ packages }}'
    state: latest

- name: Harden ssh config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Restart sshd
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed
